# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc94df6186bdab8bb973ebf08ce885e4dd0d5132b4a65b8eb6876400fae057550f40c93df16bc4d008a9c7836ae416986476a057a7f418a34897e5da73a163a

test:
  secret_key_base: a954c2c69eb11238705d029ca3ac6a07a3e7c292fdf56589de902b2df0b0081fe15071890292be55b0e9bab49b047a909791defd7abd7c82d05750c1d1b28d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
